services:
  db:
    image: postgres:15-alpine
    container_name: nexus_db
    environment:
      POSTGRES_USER: fast_api
      POSTGRES_PASSWORD: fast_api
      POSTGRES_DB: fast_api_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fast_api"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nexus_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://fast_api:fast_api@db:5432/fast_api_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app
    networks:
      - nexus_network

  frontend:
    build:
      context: ./daisyui-vue-client
      dockerfile: Dockerfile
    container_name: nexus_frontend
    ports:
      - "5173:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./daisyui-vue-client/src:/usr/src/app/src
    networks:
      - nexus_network

volumes:
  postgres_data:

networks:
  nexus_network:
    driver: bridge
